# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b0fd5adc782234779c8d4942affcbce88f8aed8969c2c86ee734a58fee0ecc717cd72100c21f44173d5631a98f7c3f32745906750553120e308cdb700339d0e

test:
  secret_key_base: dbf4b581dfd018bd27610f257785af9d33e031f80d734e181cf3e4da2be8a7b7d9fb09d03dfe854515e1c8956ff9d471b516c0d0c4c33c22f8903278e78bb121

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
